### ISSUE TITLE
почему jodaTime?

### ISSUE THREAD

**Issue by olshevskiy87** [ShoshinNikita/habrahabr-bot-go#1]
в `src/logging/logging.go` в функции `GetCurrentTime()` вместо
`jodaTime.Format("dd.MM.yyyy HH:mm:ss", time.Now())`
можно написать
`time.Now().Format("02.01.2006 15:04:05")`
и таким образом избавиться от лишней зависимости. или это запас удобства на будущее?)

**Comment by ShoshinNikita** [comment]
Запас удобств. Да и, если честно, мне не очень нравится писать абстрактные даты вместо `dd.MM.yyyy`
